title: Blog et Portfolio de Vanak Lay
markdown: kramdown
url: ""

# for atom feed
author:
  name: Vanak Lay
  email: contact@vanaklay.com
  image: "https://avatars0.githubusercontent.com/u/49145563?s=120&v=4"
  bio: "Développeur indépendant basé à Paris qui accompagne les Startups dans la création de leur MVP ou 
  dans le développement de leurs applications webs et mobiles grâce à la stack React, React Native, Javascript, Ruby et Ruby on Rails."
  github: "vanaklay"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
