title: Développeur web
markdown: kramdown
url: ""

# for atom feed
author:
  name: Vanak Lay
  email: contact@vanaklay.com
  image: "https://avatars0.githubusercontent.com/u/49145563?s=120&v=4"
  bio: "Développeur back-end basé à Paris qui accompagne les Startups 
  dans le développement de leurs applications webs grâce à ASP.NET, Ruby On Rails."
  github: "vanaklay"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/db"
    values:
      image: true
